#!/bin/sh

function do_curl() {
    declare -a argv=(curl --trace-ascii - --header 'Host: ping.example' "$@")
    echo "run ${argv[@]}"
    "${argv[@]}"
    local e=$?
    echo "${argv[0]} exit $e"
    return $e
}

function show_last_few() {
    echo "--- the last few in $1 -------------------------------------------"
    tail -5 $1
}

echo
echo "--- GET -------------------------------------------"
# expect adonishment of failure
do_curl http://localhost:8888/scarpet
# expect adonishment of failure
do_curl http://localhost:8888/scarpet/
# This could work if there was a DID (document) available there c.f. https://w3c-ccg.github.io/did-spec/
do_curl http://localhost:8888/scarpet/did:example:123456789abcdefghi
echo "--- POST -------------------------------------------"
do_curl -d example.1.zone-that http://localhost:8888/scarpet
echo "--- PUT -------------------------------------------"
do_curl -X PUT -d example.2.zone http://localhost:8888/scarpet/did:example:123456789abcdefghi
echo

# var probably contains data files (the scarpet local storage)
ls -als ${0%/*}/{var,logs}
show_last_few logs/access_log
show_last_few logs/error_log
